language: r
cache: packages

install:
- Rscript install.R

script:
- Rscript forecast_R_to_github.R

deploy:
prodiver: pages
skip_cleanup: true
github_token: $GITHUB_TOKEN
keep_history: true
target_branch: master
