language: r
cache: packages

install:
  - Rscript -e "print('skipping standard install')"
  - Rscript install.R
  
script:
  - Rscript forecast_R_to_github.R
  

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  target_branch: master
